api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "engraving-cart-transform"
type = "function"
uid = "a6a964d1-10a4-e495-6e97-b56a9ab56bc6cbeeb33b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
